### PR TITLE
Extract test utils into src namespace

### PR DESCRIPTION
**Pull request by michihuber**
Extracts test utils from `test/` dir ns to `src/` dir ns. This allows library users to use the test utils for integration tests.

### CODE REVIEW

**Comment by yogthos** [comment]
Makes sense, just pushed out 2.5.7 with the change.

**Comment by michihuber** [comment]
thank you!

one question: are the tests reliable or do you get occasional flakiness? we're seeing some on our end...

**Comment by yogthos** [comment]
There can be some flakiness since the content of the pdf has some system dependencies like local fonts. It's more of a sanity check right now, but for any major changes I tend to do a visual inspection manually.

**Comment by michihuber** [comment]
Gotcha, thank you, much appreciated!

**Pull request merged**
