### PR TITLE
Various bug fixes

### PR DESCRIPTION
**Pull request by arational**
Add various bug fixes. See commit messages for details.
They are all in one PR, so if desired, I can separate each commit in an own PR.

### CODE REVIEW

**Comment by yogthos** [comment]
Looks good, could you just do a rebase to the latest? :)

**Comment by arational** [comment]
Alright, it's rebased now. :-)

**Comment by yogthos** [comment]
Awesome, just pushed out `2.6.7` with the fixes and file attachments support.

**Comment by arational** [comment]
Thanks a lot!

**Comment by yogthos** [comment]
Thanks for doing the PRs, much appreciated. :)

**Comment by leafgarland** [comment]
I might have missed it in the docs, but this PR's change to make chart and svg sections optional broke for us as we were using `:image` tags without explicitly requiring the chart section. It's an easy fix but it took me a little while to figure out what was wrong.

If I didn't miss it in the docs then it might be worth mentioning somewhere that some tags require these explicit requires. Cheers.

**Comment by yogthos** [comment]
I wonder if it might make sense to require the ns by default, I'm not sure the benefit of saving a bit of memory is worth the regression in the ergonomics.

**Comment by leafgarland** [comment]
Personally, I agree. My fix was to include both chart and svg anyway, even though I'm probably not using anything from svg. It didn't seem worth the effort of figuring out which tags are in which namespaces.

If the reduction in memory (and perhaps load time) is worth while, then a table in the README that lists which tags are in which section/namespace would help.

**Comment by yogthos** [comment]
I ended up pushing out `2.6.8` with the requires back by default. It's not that big of an overhead in practice, but we could look at making this configurable as an opt out.

**Pull request merged**
